import React, { useState, useEffect } from "react";
import BillService from "../Services/BillService";
import { getAllUsers } from "../Services/UserService";

const BillDetails = () => {
  const [bills, setBills] = useState([]);
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedBill, setSelectedBill] = useState(null);
  const [showBillModal, setShowBillModal] = useState(false);

  useEffect(() => {
    fetchBills();
    fetchUsers();
  }, []);

  const fetchBills = async () => {
    setLoading(true);
    try {
      const res = await BillService.getAllBills();
      setBills(res);
    } catch (err) {
      alert("Failed to fetch bills");
    }
    setLoading(false);
  };

  const fetchUsers = async () => {
    try {
      const res = await getAllUsers();
      //console.log("API users:", res.data);
      setUsers(res.data.filter((u) => u.role === "ROLE_RESIDENT"));
    } catch (err) {
      setUsers([]);
    }
  };

  return (
    <div
      className="modal show d-block"
      style={{ backgroundColor: "rgba(0,0,0,0.5)" }}
      onClick={() => setShowBillModal(false)}
    >
      <div
        className="modal-dialog modal-dialog-centered"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="modal-content">
          <div className="modal-header">
            <h5 className="modal-title">Bill Details</h5>
            <button
              type="button"
              className="btn-close"
              onClick={() => setShowBillModal(false)}
            ></button>
          </div>
          <div className="modal-body">
            <p>
              <strong>Bill Number:</strong> {selectedBill.billNumber}
            </p>
            <p>
              <strong>Bill Date:</strong> {selectedBill.billDate}
            </p>
            <p>
              <strong>Due Date:</strong> {selectedBill.dueDate}
            </p>
            <p>
              <strong>Resident:</strong> {selectedBill.resident?.firstName}{" "}
              {selectedBill.resident?.lastName} (Flat:{" "}
              {selectedBill.resident?.flatNo})
            </p>
            <p>
              <strong>Type:</strong> {selectedBill.type || "Maintenance"}
            </p>
            <p>
              <strong>Description:</strong> {selectedBill.description}
            </p>
            <p>
              <strong>Maintenance Amount:</strong> ₹
              {selectedBill.maintenanceAmount}
            </p>
            <p>
              <strong>Penalty Amount:</strong> ₹{selectedBill.penaltyAmount}
            </p>
            <p>
              <strong>Total Amount:</strong> ₹{selectedBill.totalAmount}
            </p>
            <p>
              <strong>Status:</strong>
              <span
                className={`badge ms-2 ${
                  selectedBill.payment
                    ? "bg-success"
                    : new Date(selectedBill.dueDate) < new Date()
                    ? "bg-danger"
                    : "bg-warning"
                }`}
              >
                {selectedBill.payment
                  ? "PAID"
                  : new Date(selectedBill.dueDate) < new Date()
                  ? "OVERDUE"
                  : "PENDING"}
              </span>
            </p>
            <p>
              <strong>Generated By:</strong>{" "}
              {selectedBill.generatedBy?.firstName}{" "}
              {selectedBill.generatedBy?.lastName}
            </p>
          </div>
          <div className="modal-footer">
            <button
              type="button"
              className="btn btn-secondary"
              onClick={() => setShowBillModal(false)}
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BillDetails;
